site_name: 哈工大航模协会火箭组


theme:                      # 主题
  name: material            # 更多的MkDocs主题请参看官方网页，此处选用了material主题 https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
  icon:
    logo: material/rocket   # 图标设置
  language: zh              # 更改语言
  palette:
    # 明亮模式
    - scheme: default
      primary: indigo       # 更改横幅颜色
      toggle:
        icon: material/brightness-7 
        name: 切换到暗色模式
    # 暗色模式
    - scheme: slate
      primary: black        # 更改横幅颜色
      toggle:
        icon: material/brightness-3
        name: 切换到明亮模式
  font:
    text: Roboto            # 字体设置 
  
  features:
    - navigation.top        # 返回顶部按钮
    - navigation.tabs       # 顶部分类标签
    - search.highlight      # 搜索结果高亮显示


plugins:
  - glightbox


nav:                        # 定义文章的顺序与链接
- 入门:
  - 火箭组介绍: 首页文章\总体介绍.md

- 注意事项及参考资料:
  - 手工注意事项: 技术文章\手工注意事项.md
  - 外场准备及外场注意事项: 技术文章\外场准备及外场注意事项.md
  - 外场箱整理: 技术文章\外场箱整理.md
  - 发动机基本信息表: 技术文章\发动机基本信息表.md

- 安全:
  - 日常安全守则: 安全须知\日常安全.md
  - 外场安全: 安全须知\外场安全.md

- 网站维护:
  - 本站搭建简易教程: 网站维护\本站搭建简易教程.md


markdown_extensions:              # 插件
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption       # 便捷的图像标题编辑

copyright: © 1990 - 2025 哈尔滨工业大学航模协会 All Rights Reserved